import React from 'react'
import { Outfit } from 'next/font/google'


const inter = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple: ['/apple-touch-icon.png?v=4'],
    shortcut: ['/apple-touch-icon.png']
  },
  manifest: '/site.webmanifest'
}


function layout({ children }) {
   
    return (
      <div>
        {children}
      </div>
    )
  }
  
  export default layout